export const TAKEOFF_MODULE_ENABLED_FLAG_KEY = "TAKEOFF_MODULE_ENABLED";

export const TAKEOFF_C_CHUNK_THRESHOLD_PAGES_FLAG_KEY =
  "TAKEOFF_C_CHUNK_THRESHOLD_PAGES";
export const TAKEOFF_C_CHUNK_SIZE_PAGES_FLAG_KEY = "TAKEOFF_C_CHUNK_SIZE_PAGES";
export const TAKEOFF_C_CHUNK_OVERLAP_PAGES_FLAG_KEY =
  "TAKEOFF_C_CHUNK_OVERLAP_PAGES";
export const TAKEOFF_C_MAX_PDF_PAGES_FLAG_KEY = "TAKEOFF_C_MAX_PDF_PAGES";
export const TAKEOFF_C_TIMEOUT_MS_FLAG_KEY = "TAKEOFF_C_TIMEOUT_MS";
export const TAKEOFF_C_MAX_TOTAL_TOKENS_FLAG_KEY =
  "TAKEOFF_C_MAX_TOTAL_TOKENS";
export const TAKEOFF_C_MAX_COST_CENTS_FLAG_KEY = "TAKEOFF_C_MAX_COST_CENTS";

export const TAKEOFF_C_CHUNK_THRESHOLD_PAGES_DEFAULT = 15;
export const TAKEOFF_C_CHUNK_SIZE_PAGES_DEFAULT = 10;
export const TAKEOFF_C_CHUNK_OVERLAP_PAGES_DEFAULT = 2;
export const TAKEOFF_C_MAX_PDF_PAGES_DEFAULT = 200;
export const TAKEOFF_C_TIMEOUT_MS_DEFAULT = 300_000;
export const TAKEOFF_C_TIMEOUT_MS_MIN = 120_000;
export const TAKEOFF_C_TIMEOUT_MS_MAX = 900_000;
export const TAKEOFF_C_MAX_TOTAL_TOKENS_DEFAULT = 400_000;
export const TAKEOFF_C_MAX_COST_CENTS_DEFAULT = 2_500;
