export const TAKEOFF_MODULE_ENABLED_FLAG_KEY = "TAKEOFF_MODULE_ENABLED";

export const TAKEOFF_C_CHUNK_THRESHOLD_PAGES_FLAG_KEY =
  "TAKEOFF_C_CHUNK_THRESHOLD_PAGES";
export const TAKEOFF_C_CHUNK_SIZE_PAGES_FLAG_KEY = "TAKEOFF_C_CHUNK_SIZE_PAGES";
export const TAKEOFF_C_CHUNK_OVERLAP_PAGES_FLAG_KEY =
  "TAKEOFF_C_CHUNK_OVERLAP_PAGES";
export const TAKEOFF_C_MAX_PDF_PAGES_FLAG_KEY = "TAKEOFF_C_MAX_PDF_PAGES";
export const TAKEOFF_C_TIMEOUT_MS_FLAG_KEY = "TAKEOFF_C_TIMEOUT_MS";
export const TAKEOFF_C_MAX_TOTAL_TOKENS_FLAG_KEY =
  "TAKEOFF_C_MAX_TOTAL_TOKENS";
export const TAKEOFF_C_MAX_COST_CENTS_FLAG_KEY = "TAKEOFF_C_MAX_COST_CENTS";
export const TAKEOFF_LOW_CONFIDENCE_THRESHOLD_FLAG_KEY =
  "TAKEOFF_LOW_CONFIDENCE_THRESHOLD";
export const TAKEOFF_AI_ESCALATION_ENABLED_FLAG_KEY =
  "TAKEOFF_AI_ESCALATION_ENABLED";
export const TAKEOFF_AI_ESCALATION_MIN_CONFIDENCE_FLAG_KEY =
  "TAKEOFF_AI_ESCALATION_MIN_CONFIDENCE";
export const TAKEOFF_AI_ESCALATION_MAX_COST_CENTS_FLAG_KEY =
  "TAKEOFF_AI_ESCALATION_MAX_COST_CENTS";
export const TAKEOFF_GEMINI_BATCH_MODE_FLAG_KEY = "TAKEOFF_GEMINI_BATCH_MODE";

export const TAKEOFF_C_CHUNK_THRESHOLD_PAGES_DEFAULT = 15;
export const TAKEOFF_C_CHUNK_SIZE_PAGES_DEFAULT = 10;
export const TAKEOFF_C_CHUNK_OVERLAP_PAGES_DEFAULT = 2;
export const TAKEOFF_C_MAX_PDF_PAGES_DEFAULT = 200;
export const TAKEOFF_C_TIMEOUT_MS_DEFAULT = 300_000;
export const TAKEOFF_C_TIMEOUT_MS_MIN = 120_000;
export const TAKEOFF_C_TIMEOUT_MS_MAX = 900_000;
export const TAKEOFF_C_MAX_TOTAL_TOKENS_DEFAULT = 400_000;
export const TAKEOFF_C_MAX_COST_CENTS_DEFAULT = 2_500;
export const TAKEOFF_AI_ESCALATION_ENABLED_DEFAULT = false;
export const TAKEOFF_AI_ESCALATION_MIN_CONFIDENCE_DEFAULT = 0.75;
export const TAKEOFF_AI_ESCALATION_MAX_COST_CENTS_DEFAULT = 500;
export const TAKEOFF_GEMINI_BATCH_MODE_DEFAULT = false;

export const TAKEOFF_PROCESSING_LEASE_TTL_SECONDS = 30 * 60;
export const TAKEOFF_BATCH_RECONCILE_LEASE_TTL_SECONDS = 5 * 60;
export const TAKEOFF_BATCH_RECONCILE_BACKOFF_SECONDS = [10, 20, 40, 60] as const;
export const TAKEOFF_BATCH_RECONCILE_MAX_ATTEMPTS = 24;
