import { z } from "zod";

import { estimateApprovalActionSchema } from "@/lib/approvals/schemas";
import {
  createMissingPriceImportEntitiesSchema,
  resolvePriceImportSuggestionsSchema,
} from "@/lib/catalogue/schemas";
import {
  applyEstimateStructureDraftSchema,
  duplicateEstimateSectionSchema,
  generateEstimateStructureDraftSchema,
  generateVersionZeroDraftSchema,
  importEstimateSectionsSchema,
  importLinkedDpgfSourceSchema,
  reviewVersionZeroLineSchema,
} from "@/lib/estimates/schemas";
import {
  buildOpenApiRouteOperation,
  csvResponseDefinition,
  genericOkResponseDefinition,
  insertTemplateIntoVersionBodySchema,
  jobIdParameter,
  portalAcceptSchema,
  portalRejectSchema,
  purchaseOrderCreateSchema,
  purchaseOrderDevisFormSchema,
  purchaseOrderDevisPatchSchema,
  purchaseOrderDevisReorderSchema,
  purchaseOrderUpdateSchema,
  routeContractUuidSchema as uuidSchema,
  takeoffItemsPatchSchema,
  takeoffPlanSetUpdateSchema,
  versionIdParameter,
  type RouteContract,
} from "@/lib/openapi/route-contracts";
import type { OpenApiOperationDefinition } from "@/lib/openapi/registry";
const portalAndProcurementContracts: RouteContract[] = [
  {
    id: "accept-portal-estimate",
    method: "post",
    path: "/api/portal/{token}/accept",
    summary: "Accepter un devis depuis le portail",
    description:
      "Revendique atomiquement le jeton de portail, accepte le devis et enregistre la signature optionnelle.",
    tags: ["Portail"],
    rawErrors: true,
    pathParameters: [{ name: "token", schema: z.string().min(1), description: "Jeton de capacite du portail." }],
    body: { schema: portalAcceptSchema, description: "Acceptation des conditions et signature PNG optionnelle." },
    success: [
      {
        status: "200",
        description: "Devis accepte.",
        rawJson: true,
        schema: {
          schemaName: "PortalEstimateAcceptedResponse",
          schema: z.object({ status: z.literal("accepted"), accepted_at: z.string() }),
          io: "output",
        },
      },
    ],
    extraErrors: [{ status: "503", description: "Document contractuel temporairement indisponible." }],
  },
  {
    id: "reject-portal-estimate",
    method: "post",
    path: "/api/portal/{token}/reject",
    summary: "Refuser un devis depuis le portail",
    description: "Revendique atomiquement le jeton de portail et refuse le devis.",
    tags: ["Portail"],
    rawErrors: true,
    pathParameters: [{ name: "token", schema: z.string().min(1), description: "Jeton de capacite du portail." }],
    body: { schema: portalRejectSchema, description: "Motif optionnel du refus.", required: false },
    success: [
      {
        status: "200",
        description: "Devis refuse.",
        rawJson: true,
        schema: {
          schemaName: "PortalEstimateRejectedResponse",
          schema: z.object({ status: z.literal("rejected") }),
          io: "output",
        },
      },
    ],
  },
  {
    id: "list-prices",
    method: "get",
    path: "/api/prices",
    summary: "Lister les prix fournisseurs",
    description:
      "Retourne une liste, une page ou une fiche fournisseur-produit selon le parametre `view`.",
    tags: ["Catalogue"],
    queryParameters: [
      { name: "view", schema: z.enum(["page", "supplier-item"]), description: "Vue de lecture." },
      { name: "supplier_id", schema: uuidSchema, description: "Fournisseur cible." },
      { name: "product_id", schema: uuidSchema, description: "Produit cible." },
      { name: "catalogue_item_id", schema: uuidSchema, description: "Alias historique du produit." },
      { name: "limit", schema: z.number().int().positive().max(1000), description: "Limite de la liste." },
      { name: "q", schema: z.string().max(200), description: "Recherche de la vue paginee." },
      { name: "freshness", schema: z.array(z.enum(["fresh", "aging", "stale"])), description: "Filtres de fraicheur." },
      { name: "sort", schema: z.enum(["supplier", "product", "unit_price_cents", "updated_at"]), description: "Colonne de tri." },
      { name: "dir", schema: z.enum(["asc", "desc"]), description: "Direction du tri." },
      { name: "page", schema: z.number().int().positive(), description: "Page demandee." },
      { name: "size", schema: z.union([z.literal(25), z.literal(50), z.literal(100)]), description: "Taille de page." },
    ],
  },
  {
    id: "list-price-lookups",
    method: "get",
    path: "/api/prices/lookups",
    summary: "Rechercher fournisseurs et produits",
    description: "Retourne les suggestions de lookup pour l'import de prix.",
    tags: ["Catalogue"],
    queryParameters: [
      { name: "kind", schema: z.enum(["supplier", "product", "all"]), description: "Type de recherche." },
      { name: "q", schema: z.string().max(200), description: "Recherche textuelle." },
      { name: "selected_id", schema: uuidSchema, description: "Element a conserver dans les resultats." },
      { name: "limit", schema: z.number().int().positive().max(50), description: "Nombre maximal de resultats." },
    ],
  },
  {
    id: "resolve-price-import",
    method: "post",
    path: "/api/prices/import/resolve",
    summary: "Resoudre les inconnus d'un import de prix",
    description: "Propose les correspondances fournisseurs et produits pour les valeurs inconnues.",
    tags: ["Catalogue"],
    body: { schema: resolvePriceImportSuggestionsSchema, description: "Noms fournisseurs et produits inconnus." },
  },
  {
    id: "create-missing-price-entities",
    method: "post",
    path: "/api/prices/import/create-missing",
    summary: "Creer les entites manquantes d'un import de prix",
    description: "Cree les fournisseurs et produits selectionnes avant import.",
    tags: ["Catalogue"],
    body: { schema: createMissingPriceImportEntitiesSchema, description: "Entites a creer." },
  },
  {
    id: "create-purchase-order",
    method: "post",
    path: "/api/purchase-orders",
    summary: "Creer un bon de commande",
    description: "Cree un bon de commande brouillon et ses lignes calculees.",
    tags: ["Achats"],
    rawErrors: true,
    body: { schema: purchaseOrderCreateSchema, description: "Fournisseur, chantier et lignes de commande." },
    success: [
      {
        status: "200",
        description: "Bon de commande cree.",
        rawJson: true,
        schema: {
          schemaName: "PurchaseOrderCreatedResponse",
          schema: z.object({ id: uuidSchema, reference: z.string() }),
          io: "output",
        },
      },
    ],
  },
  {
    id: "update-purchase-order",
    method: "put",
    path: "/api/purchase-orders/{id}",
    summary: "Modifier un bon de commande brouillon",
    description: "Remplace atomiquement les champs et lignes fournis du brouillon.",
    tags: ["Achats"],
    rawErrors: true,
    pathParameters: [{ name: "id", schema: uuidSchema, description: "Identifiant du bon de commande." }],
    body: { schema: purchaseOrderUpdateSchema, description: "Champs et lignes a remplacer." },
    success: [{ status: "200", description: "Bon de commande modifie.", rawJson: true }],
  },
  {
    id: "delete-purchase-order",
    method: "delete",
    path: "/api/purchase-orders/{id}",
    summary: "Supprimer un bon de commande brouillon",
    description: "Supprime atomiquement le brouillon et programme le nettoyage Storage.",
    tags: ["Achats"],
    rawErrors: true,
    pathParameters: [{ name: "id", schema: uuidSchema, description: "Identifiant du bon de commande." }],
    success: [{ status: "200", description: "Bon de commande supprime.", rawJson: true }],
  },
  {
    id: "list-purchase-order-quotes",
    method: "get",
    path: "/api/purchase-orders/{id}/devis",
    summary: "Lister les devis fournisseur d'un bon de commande",
    description: "Retourne les devis joints avec URLs temporaires de telechargement.",
    tags: ["Achats"],
    rawErrors: true,
    pathParameters: [{ name: "id", schema: uuidSchema, description: "Identifiant du bon de commande." }],
    success: [{ status: "200", description: "Devis joints retournes.", rawJson: true }],
  },
  {
    id: "create-purchase-order-quote",
    method: "post",
    path: "/api/purchase-orders/{id}/devis",
    summary: "Joindre un devis fournisseur",
    description: "Valide, stocke et rattache un fichier au bon de commande.",
    tags: ["Achats"],
    rawErrors: true,
    pathParameters: [{ name: "id", schema: uuidSchema, description: "Identifiant du bon de commande." }],
    body: { schema: purchaseOrderDevisFormSchema, description: "Fichier devis et nom d'affichage optionnel.", contentType: "multipart/form-data" },
    success: [{ status: "201", description: "Devis joint.", rawJson: true }],
  },
  {
    id: "patch-purchase-order-quote",
    method: "patch",
    path: "/api/purchase-orders/{id}/devis/{devisId}",
    summary: "Renommer un devis fournisseur",
    description: "Met a jour le nom d'affichage du devis joint.",
    tags: ["Achats"],
    rawErrors: true,
    pathParameters: [
      { name: "id", schema: uuidSchema, description: "Identifiant du bon de commande." },
      { name: "devisId", schema: uuidSchema, description: "Identifiant du devis joint." },
    ],
    body: { schema: purchaseOrderDevisPatchSchema, description: "Nouveau nom d'affichage." },
    success: [{ status: "200", description: "Devis renomme.", rawJson: true }],
  },
  {
    id: "delete-purchase-order-quote",
    method: "delete",
    path: "/api/purchase-orders/{id}/devis/{devisId}",
    summary: "Supprimer un devis fournisseur",
    description: "Supprime le fichier Storage et son rattachement au bon de commande.",
    tags: ["Achats"],
    rawErrors: true,
    pathParameters: [
      { name: "id", schema: uuidSchema, description: "Identifiant du bon de commande." },
      { name: "devisId", schema: uuidSchema, description: "Identifiant du devis joint." },
    ],
    success: [{ status: "200", description: "Devis supprime.", rawJson: true }],
  },
  {
    id: "reorder-purchase-order-quotes",
    method: "patch",
    path: "/api/purchase-orders/{id}/devis/reorder",
    summary: "Reordonner les devis fournisseur",
    description: "Applique atomiquement l'ordre exhaustif des devis joints.",
    tags: ["Achats"],
    rawErrors: true,
    pathParameters: [{ name: "id", schema: uuidSchema, description: "Identifiant du bon de commande." }],
    body: { schema: purchaseOrderDevisReorderSchema, description: "Liste ordonnee exhaustive des devis." },
    success: [{ status: "200", description: "Devis reordonnes.", rawJson: true }],
  },
  {
    id: "download-purchase-order-archive",
    method: "get",
    path: "/api/purchase-orders/{id}/zip",
    summary: "Telecharger l'archive d'un bon de commande",
    description: "Diffuse un ZIP contenant le bon de commande HTML et ses devis accessibles.",
    tags: ["Achats"],
    rawErrors: true,
    pathParameters: [{ name: "id", schema: uuidSchema, description: "Identifiant du bon de commande." }],
    success: [{ status: "200", description: "Archive ZIP diffusee.", contentType: "application/zip" }],
  },
];

const estimateWorkflowContracts: RouteContract[] = [
  {
    id: "get-estimate-approval-journal",
    method: "get",
    path: "/api/estimates/{versionId}/approval-journal",
    summary: "Consulter le journal de decision d'un devis",
    description: "Retourne le journal d'approbation en JSON ou CSV selon `format`.",
    tags: ["Estimates"],
    pathParameters: [versionIdParameter],
    queryParameters: [
      { name: "author", schema: uuidSchema, description: "Auteur de decision a filtrer." },
      { name: "status", schema: z.enum(["approved", "approved_with_reservations", "changes_requested"]), description: "Decision a filtrer." },
      { name: "format", schema: z.enum(["json", "csv"]), description: "Format de sortie." },
    ],
    success: [
      {
        status: "200",
        description: "Journal retourne.",
        contents: [
          { contentType: "application/json", schema: genericOkResponseDefinition },
          { contentType: "text/csv", schema: csvResponseDefinition },
        ],
      },
    ],
  },
  {
    id: "get-estimate-approval",
    method: "get",
    path: "/api/estimates/{versionId}/approval",
    summary: "Consulter la synthese d'approbation",
    description: "Retourne les regles, demandes et decisions de la version de devis.",
    tags: ["Estimates"],
    pathParameters: [versionIdParameter],
  },
  {
    id: "post-estimate-approval",
    method: "post",
    path: "/api/estimates/{versionId}/approve",
    summary: "Piloter l'approbation d'un devis",
    description: "Demande, soumet, approuve, rejette ou decide l'approbation de la version.",
    tags: ["Estimates"],
    pathParameters: [versionIdParameter],
    body: { schema: estimateApprovalActionSchema, description: "Action d'approbation discriminee." },
    success: [
      { status: "200", description: "Decision d'approbation executee." },
      { status: "201", description: "Demande d'approbation creee." },
    ],
  },
  {
    id: "list-estimate-draft-versions",
    method: "get",
    path: "/api/estimates/{versionId}/draft-versions",
    summary: "Lister les versions brouillon du projet",
    description: "Retourne les versions brouillon rattachees au meme projet que la version cible.",
    tags: ["Estimates"],
    pathParameters: [versionIdParameter],
  },
  {
    id: "import-linked-dpgf",
    method: "post",
    path: "/api/estimates/{versionId}/import-linked-dpgf",
    summary: "Importer la source DPGF liee",
    description: "Importe la source DPGF canonique rattachee a l'affaire dans la version cible.",
    tags: ["Estimates"],
    pathParameters: [versionIdParameter],
    body: { schema: importLinkedDpgfSourceSchema, description: "Titre de section optionnel.", required: false },
    success: [{ status: "201", description: "Source DPGF importee." }],
  },
  {
    id: "import-estimate-sections",
    method: "post",
    path: "/api/estimates/{versionId}/import-sections",
    summary: "Importer des sections d'une autre version",
    description: "Copie une selection de sections dans la version cible en mode append ou merge.",
    tags: ["Estimates"],
    pathParameters: [versionIdParameter],
    body: { schema: importEstimateSectionsSchema, description: "Version source, sections et mode d'import." },
    success: [{ status: "201", description: "Sections importees." }],
  },
  {
    id: "duplicate-estimate-section",
    method: "post",
    path: "/api/estimates/{versionId}/sections/{sectionId}/duplicate",
    summary: "Dupliquer une section de devis",
    description: "Duplique la section source dans une version cible optionnelle.",
    tags: ["Estimates"],
    pathParameters: [
      versionIdParameter,
      { name: "sectionId", schema: uuidSchema, description: "Identifiant de la section." },
    ],
    body: { schema: duplicateEstimateSectionSchema, description: "Version cible optionnelle.", required: false },
    success: [{ status: "201", description: "Section dupliquee." }],
  },
  {
    id: "list-estimate-sections",
    method: "get",
    path: "/api/estimates/{versionId}/sections",
    summary: "Lister les sections importables",
    description: "Retourne les sections de la version accessibles au workflow d'import.",
    tags: ["Estimates"],
    pathParameters: [versionIdParameter],
  },
  {
    id: "generate-estimate-structure-draft",
    method: "post",
    path: "/api/estimates/{versionId}/structure-drafts",
    summary: "Generer un brouillon de structure",
    description: "Produit un brouillon de structure hybride depuis les sources disponibles.",
    tags: ["Estimates"],
    pathParameters: [versionIdParameter],
    body: { schema: generateEstimateStructureDraftSchema, description: "Strategie de generation." },
    success: [{ status: "201", description: "Brouillon de structure genere." }],
  },
  {
    id: "get-estimate-structure-draft",
    method: "get",
    path: "/api/estimates/{versionId}/structure-drafts/{draftId}",
    summary: "Consulter un brouillon de structure",
    description: "Retourne le brouillon de structure rattache a la version.",
    tags: ["Estimates"],
    pathParameters: [
      versionIdParameter,
      { name: "draftId", schema: uuidSchema, description: "Identifiant du brouillon." },
    ],
  },
  {
    id: "apply-estimate-structure-draft",
    method: "post",
    path: "/api/estimates/{versionId}/structure-drafts/{draftId}/apply",
    summary: "Appliquer un brouillon de structure",
    description: "Materialise les noeuds selectionnes selon le mode et les overrides fournis.",
    tags: ["Estimates"],
    pathParameters: [
      versionIdParameter,
      { name: "draftId", schema: uuidSchema, description: "Identifiant du brouillon." },
    ],
    body: { schema: applyEstimateStructureDraftSchema, description: "Mode, noeuds selectionnes et overrides." },
    success: [{ status: "201", description: "Brouillon applique." }],
  },
  {
    id: "list-version-zero-drafts",
    method: "get",
    path: "/api/estimates/{versionId}/version-zero-drafts",
    summary: "Consulter la synthese des versions zero",
    description: "Retourne la synthese du dernier brouillon version zero.",
    tags: ["Estimates"],
    pathParameters: [versionIdParameter],
  },
  {
    id: "generate-version-zero-draft",
    method: "post",
    path: "/api/estimates/{versionId}/version-zero-drafts",
    summary: "Generer une version zero",
    description: "Genere un brouillon IA a revoir pour les lots selectionnes.",
    tags: ["Estimates"],
    pathParameters: [versionIdParameter],
    body: { schema: generateVersionZeroDraftSchema, description: "Brief et lots selectionnes." },
    success: [{ status: "201", description: "Brouillon version zero genere." }],
  },
  {
    id: "get-version-zero-draft",
    method: "get",
    path: "/api/estimates/{versionId}/version-zero-drafts/{draftId}",
    summary: "Consulter une version zero",
    description: "Retourne le detail de revue du brouillon version zero.",
    tags: ["Estimates"],
    pathParameters: [
      versionIdParameter,
      { name: "draftId", schema: uuidSchema, description: "Identifiant du brouillon." },
    ],
  },
  {
    id: "materialize-version-zero-draft",
    method: "post",
    path: "/api/estimates/{versionId}/version-zero-drafts/{draftId}/materialize",
    summary: "Materialiser une version zero",
    description: "Cree les elements de devis depuis un brouillon version zero pret.",
    tags: ["Estimates"],
    pathParameters: [
      versionIdParameter,
      { name: "draftId", schema: uuidSchema, description: "Identifiant du brouillon." },
    ],
    success: [{ status: "201", description: "Version zero materialisee." }],
  },
  {
    id: "review-version-zero-line",
    method: "patch",
    path: "/api/estimates/{versionId}/version-zero-drafts/{draftId}/lines/{lineDraftId}",
    summary: "Revoir une ligne de version zero",
    description: "Accepte, edite ou rejette une ligne du brouillon version zero.",
    tags: ["Estimates"],
    pathParameters: [
      versionIdParameter,
      { name: "draftId", schema: uuidSchema, description: "Identifiant du brouillon." },
      { name: "lineDraftId", schema: uuidSchema, description: "Identifiant de la ligne brouillon." },
    ],
    body: { schema: reviewVersionZeroLineSchema, description: "Decision de revue et valeurs editees optionnelles." },
  },
  {
    id: "list-estimate-import-sources",
    method: "get",
    path: "/api/estimates/import-sources",
    summary: "Lister les sources de devis importables",
    description: "Retourne les versions pouvant servir de source a une importation de sections.",
    tags: ["Estimates"],
    queryParameters: [
      { name: "exclude_version_id", schema: uuidSchema, description: "Version a exclure." },
      { name: "excludeVersionId", schema: uuidSchema, description: "Alias camelCase de l'exclusion." },
    ],
  },
  {
    id: "get-estimate-stats",
    method: "get",
    path: "/api/estimates/stats",
    summary: "Consulter les statistiques des devis",
    description: "Retourne les KPI et tendances des devis accessibles dans le tenant actif.",
    tags: ["Estimates"],
  },
  {
    id: "insert-estimate-template",
    method: "post",
    path: "/api/estimates/templates/{templateId}/insert",
    summary: "Inserer un template dans une version",
    description: "Insere le contenu du template dans la version cible a la position demandee.",
    tags: ["Estimates"],
    pathParameters: [{ name: "templateId", schema: uuidSchema, description: "Identifiant du template." }],
    queryParameters: [{ name: "versionId", schema: uuidSchema, description: "Version cible.", required: true }],
    body: { schema: insertTemplateIntoVersionBodySchema, description: "Version et position d'insertion optionnelle.", required: false },
  },
];

const takeoffOperationsContracts: RouteContract[] = [
  {
    id: "get-takeoff-activity-center",
    method: "get",
    path: "/api/takeoff/activity-center",
    summary: "Consulter le centre d'activite Takeoff",
    description: "Retourne les jobs et alertes Takeoff filtres pour une affaire.",
    tags: ["Takeoff"],
    queryParameters: [
      { name: "project_id", schema: uuidSchema, description: "Affaire cible.", required: true },
      { name: "versionId", schema: uuidSchema, description: "Version de devis cible." },
      { name: "lot", schema: z.string(), description: "Lot a filtrer." },
      { name: "planSetId", schema: uuidSchema, description: "Jeu de plans a filtrer." },
      { name: "status", schema: z.string(), description: "Statut a filtrer." },
      { name: "level", schema: z.string(), description: "Niveau a filtrer." },
      { name: "period", schema: z.string(), description: "Periode a filtrer." },
      { name: "limit", schema: z.number().positive(), description: "Nombre maximal de resultats." },
      { name: "offset", schema: z.number().min(0), description: "Decalage de pagination." },
    ],
  },
  {
    id: "get-takeoff-health",
    method: "get",
    path: "/api/takeoff/health",
    summary: "Verifier l'activation Takeoff",
    description: "Verifie que Takeoff est active pour le tenant authentifie.",
    tags: ["Takeoff"],
  },
  {
    id: "patch-takeoff-items",
    method: "patch",
    path: "/api/takeoff/jobs/{jobId}/items",
    summary: "Modifier des items Takeoff en lot",
    description: "Applique jusqu'a 100 mises a jour optimistes aux items d'un job termine.",
    tags: ["Takeoff"],
    pathParameters: [jobIdParameter],
    body: { schema: takeoffItemsPatchSchema, description: "Items, jetons updated_at et champs a modifier." },
  },
  {
    id: "reconcile-takeoff-job",
    method: "post",
    path: "/api/takeoff/jobs/{jobId}/reconcile",
    summary: "Reconcilier un job Takeoff",
    description: "Reconcilie l'etat du job et relance le traitement asynchrone si necessaire.",
    tags: ["Takeoff"],
    pathParameters: [jobIdParameter],
    extraErrors: [{ status: "503", description: "Worker asynchrone indisponible." }],
  },
  {
    id: "resubmit-takeoff-job",
    method: "post",
    path: "/api/takeoff/jobs/{jobId}/resubmit",
    summary: "Resoumettre un job Takeoff",
    description: "Resoumet un job eligible et declenche son traitement asynchrone.",
    tags: ["Takeoff"],
    pathParameters: [jobIdParameter],
  },
  {
    id: "patch-takeoff-plan-set",
    method: "patch",
    path: "/api/takeoff/plan-sets/{setId}",
    summary: "Modifier partiellement un jeu de plans",
    description: "Met a jour le nom, la description ou les metadonnees du jeu de plans.",
    tags: ["Takeoff"],
    pathParameters: [{ name: "setId", schema: uuidSchema, description: "Identifiant du jeu de plans." }],
    body: { schema: takeoffPlanSetUpdateSchema, description: "Champs du jeu de plans a modifier." },
  },
  {
    id: "put-takeoff-plan-set",
    method: "put",
    path: "/api/takeoff/plan-sets/{setId}",
    summary: "Modifier un jeu de plans",
    description: "Alias PUT du meme contrat de mise a jour que PATCH.",
    tags: ["Takeoff"],
    pathParameters: [{ name: "setId", schema: uuidSchema, description: "Identifiant du jeu de plans." }],
    body: { schema: takeoffPlanSetUpdateSchema, description: "Champs du jeu de plans a modifier." },
  },
];

export const workflowAdditionalOpenApiOperationsRegistry: OpenApiOperationDefinition[] = [
  ...portalAndProcurementContracts,
  ...estimateWorkflowContracts,
  ...takeoffOperationsContracts,
].map(buildOpenApiRouteOperation);
