-- EST-032 historical version retained for migration-history compatibility.
-- Its payload-constraint refresh depends on EST-164's selected supplier column
-- and is applied after that column in 20260222001500_est164_catalog_suggestions.sql.
